name: '🧨 Terraform Backend Destroy'

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: us-east-1

jobs:
  terraform:
    name: 'Destroy'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Check local/remote state
      id: check_s3
      run: |
        if aws s3 ls "s3://postech-5soat-grupo-25-tfstate" 2>&1 | grep -q 'NoSuchBucket'; then
          echo "S3_BUCKET_EXISTS=false" >> $GITHUB_ENV
        else
          echo "S3_BUCKET_EXISTS=true" >> $GITHUB_ENV
        fi

    - name: Copy state from S3 to local (if exists)
      if: env.S3_BUCKET_EXISTS == 'true'
      run: |
        aws s3 cp s3://postech-5soat-grupo-25-tfstate/backend/state  terraform.tfstate

    - name: Prepare local backend configuration
      run: |
        echo "Preparing local backend configuration..."
        > backend.tf

    - name: Initialize Terraform with local backend
      run: terraform init

    - name: Run terraform destroy
      run: terraform destroy --auto-approve
